### ISSUE TITLE
A few bugs

### ISSUE THREAD

**Issue by ghost** [bglandolt/betteranimalsplusplus#1]
1) Feral Wolves, when attacked, turn "invisible" and attack the player. They leave their visual model behind, glitching out.
https://streamable.com/51j1gu

2) Animal Swim speed is all sorts of weird. Bears can swim extremely fast, and moose can literally sprint underwater if they can touch the bottom.

Will update with more.

**Comment by bglandolt** [comment]
ty! should be all set, lmk if you have any more issues
