### ISSUE TITLE
Cannot get Zotzpyre to spawn anywhere. Also,Zotzpyre attacking other mobs puts you into 3rd person

### ISSUE THREAD

**Issue by ghost** [bglandolt/betteranimalsplusplus#2]
I have adjusted the BetterAnimalsPlus config to properly spawn Zotzpyre, but it's not working. I know the config sytax is correct, because it spawns Tarantulas properly.

I've even tried to use BiomeTweaker to force the "MONSTER" type spawn for the Zotzpyre into the game, but to no avail.

***

Also, the 3rd person "switch" that happens when you get picked up/carried by the zotzpyre is also occurring when a zotzpyre attacks other mobs (passive mobs like rabbits, cows).

When they attack these passive animals, **you** get kicked back into 3rd person, even if they're not touching you.

**Comment by Sereath** [comment]
Yeah Ive also experienced that 3rd person bug.

**Comment by bglandolt** [comment]
"I have adjusted the BetterAnimalsPlus config to properly spawn Zotzpyre, but it's not working" I do not touch spawning in this fork, so this may be a bug from the original version

However, I have fixed the "kicked back into 3rd person" bug in the latest version
