### ISSUE TITLE
Armor textures not working

### ISSUE THREAD

**Issue by AnwenFennec** [bglandolt/betteranimalsplusplus#3]
It's been some time since I last played minecraft so I'm not sure if this is a recent issue or if it was there when I downloaded the mod a while ago, but the armors no longer have textures. In the photos, i chose to show both of the lightest options of armor to show how the texture is bugged, even though its super obvious with the wolf cape i thought it would help to know.

https://imgur.com/ON6Mq0U - image 1 
https://imgur.com/sNjGMs5 - image 2

**Comment by bglandolt** [comment]
fixed!
